# Generated by Django 3.0.5 on 2020-05-02 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_auto_20200430_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='repEnfermedad',
            field=models.TextField(),
        ),
    ]
